version: '3.8'

services:
  app:
    build:
      context: .
      # Передаем переменные из .env в качестве аргументов на этап сборки
      args:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_HOST=${POSTGRES_HOST}
    container_name: lot-app-container
    restart: unless-stopped
    ports:
      - "3000:3000"
    # Эта секция по-прежнему нужна для запущенного контейнера
    env_file:
      - .env
    environment:
      - NODE_ENV=production

  postgres:
    image: postgres:16
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
